# Generated by Django 5.1.2 on 2025-03-11 04:20

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CateAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cate_num', models.IntegerField()),
                ('cate_list', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'cateanalysis',
            },
        ),
        migrations.CreateModel(
            name='CollectAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collect_num', models.IntegerField()),
                ('collect_list', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'collectanalysis',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(verbose_name='用户 ID')),
                ('fid', models.IntegerField(verbose_name='菜品 ID')),
                ('realname', models.CharField(max_length=11, verbose_name='真实姓名')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('ctime', models.DateTimeField(null=True, verbose_name='评论时间')),
            ],
            options={
                'db_table': 'comments',
            },
        ),
        migrations.CreateModel(
            name='CommentAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_num', models.IntegerField()),
                ('comment_list', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'commentanalysis',
            },
        ),
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodname', models.CharField(max_length=70, verbose_name='菜品名称')),
                ('foodtype', models.CharField(max_length=20, verbose_name='类别')),
                ('recommend', models.CharField(max_length=255, null=True, verbose_name='推荐语')),
                ('imgurl', models.CharField(max_length=255, verbose_name='图片 URL')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='价格')),
            ],
            options={
                'db_table': 'foods',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, verbose_name='用户名')),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone', models.CharField(max_length=11, unique=True)),
                ('info', models.TextField(blank=True, null=True)),
                ('face', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('addtime', models.DateTimeField(db_index=True, default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='WordAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.IntegerField()),
                ('foodtype', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'wordanalysis',
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.foods', verbose_name='菜品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.users', verbose_name='用户')),
            ],
            options={
                'db_table': 'wishlist',
                'unique_together': {('user', 'food')},
            },
        ),
    ]
